logging:
  level:
    root: INFO
    org:
      springframework:
        context: DEBUG
        jdbc:
          core: TRACE
        security:
          web:
            FilterChainProxy: DEBUG
            access: DEBUG
          oauth2:
            server:
              resource: DEBUG
  file.name: Logs/oldboy.log

datasource:
  url: jdbc:postgresql://localhost:5436/cw_db
  username: admin
  password: admin
  driver-class-name: org.postgresql.Driver
liquibase:
  enabled: true
  change_log: classpath:db/changelog/db.changelog-master.yaml
  default_schema: coworking

security:
  jwt:
    secret: 4261656C64756E674261656C64756E674261656C64756E674261656C64756E67